spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3303/ecom_db
    password: runningman
    username: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 2KB
  logging:
    level:
      org.springframework.data.jpa: DEBUG
      org.hibernate: DEBUG

application:
  security:
    jwt:
      secret-key: 40f7X6nrxgumM4h7KsamT7AZ6f9QDQDUHQtld27iFU0wxc9XIBCkkFQ9Qj7LVfMi
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8066

