spring:
  profiles:
    active: local

  security:
    user:
      name: user
      password: password
      roles: USER

    admin:
      name: admin
      password: abc@#123
      roles: ADMIN, USER

  datasource:
    url: jdbc:mysql://127.0.0.1:3303/ecom_db
    password: runningman
    username: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 2KB
  logging:
    level:
      org.springframework.data.jpa: DEBUG
      org.hibernate: DEBUG
  jackson:
    serialization:
      write-dates-as-timestamps: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      use-secret-key-for-hmac: true
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    header: Authorization


server:
  port: 8066

management:
  endpoints:
    web:
      exposure:
        include: '*'
management.endpoint.health.show-details: always

logging:
  level:
    org.springframework.security: DEBUG